name: Build Production Docker Image
on:
  push:
    branches: [ master ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Lowercase repository
        run: |
          echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest